# man 5 alacritty 查看所有配置
import = ["/Users/xingya/.config/alacritty/themes/tokyonight_moon.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "Hack Nerd Font"
style = "Italic"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["--login", "-c", "tmux new -A -s we; zsh"]
program = "/bin/zsh"

[window]
option_as_alt = "Both"
startup_mode = "SimpleFullscreen"

[window.padding]
x = 2
y = 2
