
[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"

[env]
# TERM = "xterm-256color"
TERM = "tmux-256color"

[font]
size = 11.8

[font.normal]
family = "FiraCode Nerd Font" # Hack Nerd Font
# family = "Hack Nerd Font" # Hack Nerd Font
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[terminal.shell]
args = ["--login", "-c", "tmux new -A -s main; zsh"]
program = "/bin/zsh"

[window]
option_as_alt = "Both"
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "Maximized"
# startup_mode = "SimpleFullscreen" # 问题在于如果使用了 aerospace 在切换到 该 workspace 的时候，窗口非聚焦为 alacritty 还在上个应用、需要点下鼠标才行

# decorations = "Full" | "None" | "Transparent" | "Buttonless"
decorations = "None"

[window.padding]
x = 2
y = 7

[general]
live_config_reload = true
# man 5 alacritty 查看所有配置
import = ["./theme/tokyonight_moon.toml"]

[terminal]
