# man 5 alacritty 查看所有配置
import = ["./theme/tokyonight_moon.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Off"

[env]
# TERM = "xterm-256color"
TERM = "tmux-256color"

[font]
size = 14.0

[font.normal]
family = "MesloLGM Nerd Font" # Hack Nerd Font
style = "Regular"

[font.bold]
family = "MesloLGM Nerd Font"
style = "Bold"

[font.italic]
family = "MesloLGM Nerd Font"
style = "Italic"

[font.bold_italic]
family = "MesloLGM Nerd Font"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 2

[[keyboard.bindings]]
chars = "\u001F"
key = "Slash"
mods = "Control"

[mouse]
hide_when_typing = true

[scrolling]
history = 10000

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["--login", "-c", "tmux new -A -s vn; zsh"]
program = "/bin/zsh"

[window]
option_as_alt = "Both"
# startup_mode = "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
startup_mode = "SimpleFullscreen"

[window.padding]
x = 2
y = 2
