gui:
  windowSize: "normal" # one of 'normal' | 'half' | 'full' default is 'normal'
  language: "en"
os:
  editPreset: "nvim"
git:
  log:
    showGraph: "always"
promptToReturnFromSubprocess: false
# customCommands:
#   - key: ":"
#     context: "global"
#     command: "zsh -ic"
#     subprocess: false
#     showOutput: true
