gui:
  language: "en"
  nerdFontsVersion: "3"
  commitAuthorShortLength: 6
os:
  editPreset: "nvim"
git:
  paging:
    colorArg: always
    pager: delta --paging=never --line-numbers --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
  log:
    showGraph: "always"
